apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parameter-inputs-
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: workflow-param-1
  templates:
  - name: main
    dag:
      tasks:
      - name: step-A 
        template: step-template-A
        arguments:
          parameters:
          - name: template-param-1
            value: "{{workflow.parameters.workflow-param-1}}"

  - name: step-template-A
    inputs:
      parameters:
        - name: template-param-1
    script:
      image: registry-vpc.cn-beijing.aliyuncs.com/galixir/whalesay:latest
      command: [/bin/sh]
      source: |
          echo "{{inputs.parameters.template-param-1}}"