apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: synchronization-tmpl-level-
spec:
  entrypoint: synchronization-tmpl-level-example
  templates:
  - name: synchronization-tmpl-level-example
    steps:
    - - name: synchronization-acquire-lock
        template: acquire-lock
        arguments:
          parameters:
          - name: seconds
            value: "{{item}}"
        withParam: '["1","2","3","4","5","6"]'

  - name: acquire-lock
    synchronization:
      semaphore:
        configMapKeyRef:
          name: sync-limit-3
          key: template1
    container:
      image: registry-vpc.cn-beijing.aliyuncs.com/galixir/whalesay:latest
      command: [sh, -c]
      args: ["sleep 10; echo acquired lock"]