apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-parameters-
spec:
  # serviceAccountName: argo
  securityContext:
    runAsNonRoot: false
    
  entrypoint: whalesay
  arguments:
    parameters:
      - name: message
        value: hello world
  templates:
    - name: whalesay
      inputs:
        parameters:
          - name: message
      container:
        image: registry-vpc.cn-beijing.aliyuncs.com/galixir/whalesay:latest
        command: [ cowsay ]
        args: [ "{{inputs.parameters.message}}" ] 
